name = "cmu2029"
author = "ap-1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7475b21e3e146a78296bbd0e1ff535eed41a9e56ad6810fba4ee0cafe1f9fa9a"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
