name = "cmu2029"
author = "ap-1"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58ff75e850058bdb1feb25be8a1fffc8fe79336b43c8ef03c694b5b7c4d42694"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
