name = "cmu2029"
author = "ap-1"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fdea22eb1ca44cd5a5e2d2f0536c5512f818176b43633712cb22b0d68a003cf"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
