name = "cmu2029"
author = "ap-1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c7daf85d9f3ba0e9ec961533fe9402234ed95d30c7a835db19ffa37c6c71834"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
